language: php

branches:
  only:
    - master

php:
  - 5.5
  - 5.6
#  - 7

env:
  - TYPO3_VERSION=^6.2.0
#  - TYPO3_VERSION=^7.6.0
#  - TYPO3_VERSION=dev-master

matrix:
  allow_failures:
    - env: TYPO3_VERSION=dev-master
  exclude:
    - php: 5.5
      env: TYPO3_VERSION=dev-master
    - php: 5.6
      env: TYPO3_VERSION=dev-master
#    - php: 7
#      env: TYPO3_VERSION=^7.6.0

sudo: false
cache:
  directories:
    - $HOME/.composer/cache

addons:
  apt:
    packages:
      - parallel

notifications:
  email:
    - typo3@evoweb.de

before_install:
  - phpenv config-rm xdebug.ini
  - composer self-update
  - composer --version
  - if [ "$GITHUB_COMPOSER_AUTH" ]; then composer config -g github-oauth.github.com $GITHUB_COMPOSER_AUTH; fi

before_script:
  - cd ..
  - git clone --single-branch --branch $TYPO3_BRANCH --depth 1 https://github.com/TYPO3/TYPO3.CMS.git typo3_core
  - mv typo3_core/* .
  - sudo apt-get install parallel
  - composer self-update
  - composer install
  - mkdir -p uploads typo3temp typo3conf/ext
  - mv dynaflex typo3conf/ext/
  - mv tt_address typo3conf/ext/
  - mv static_info_tables typo3conf/ext/
  - mv commerce typo3conf/ext/

script:
  - >
    echo;
    echo "Running php lint";
    find typo3conf/ext/commerce/ -name \*.php ! -path "./.Build/*" | parallel --gnu php -d display_errors=stderr -l {} > /dev/null \;

after_script:
  - >
    if [ -n "$TRAVIS_TAG" ] && [ -n "$TYPO3_ORG_USERNAME" ] && [ -n "$TYPO3_ORG_PASSWORD" ]; then
      echo -e "Preparing upload of release ${TRAVIS_TAG} to TER\n"
      curl -sSL https://raw.githubusercontent.com/alrra/travis-after-all/1.4.4/lib/travis-after-all.js | node
      if [ $? -eq 0 ]; then
        git reset --hard HEAD && git clean -fx

        TAG_MESSAGE=`git tag -n10 -l $TRAVIS_TAG | sed 's/^[0-9.]*[ ]*//g'`
        echo "Uploading release ${TRAVIS_TAG} to TER"
        .Build/bin/upload . "$TYPO3_ORG_USERNAME" "$TYPO3_ORG_PASSWORD" "$TAG_MESSAGE"
      fi;
    fi;
