<?php

$extensionPath = t3lib_extMgm::extPath('commerce');
$classPath = $extensionPath . 'Classes/';

return array(
	/* backend controller */
	'tx_commerce_controller_accesscontroller' => $classPath . 'Controller/AccessController.php',
	'sc_mod_access_perm_index' => $classPath . 'Controller/AccessController.php',
	'tx_commerce_controller_categoriescontroller' => $classPath . 'Controller/CategoriesController.php',
	'tx_commerce_categories' => $classPath . 'Controller/CategoriesController.php',
	'tx_commerce_controller_orderscontroller' => $classPath . 'Controller/OrdersController.php',
	'tx_commerce_orders' => $classPath . 'Controller/OrdersController.php',
	'tx_commerce_controller_permissionajaxcontroller' => $classPath . 'Controller/PermissionAjaxController.php',
	'sc_mod_access_perm_ajax' => $classPath . 'Controller/PermissionAjaxController.php',
	'tx_commerce_controller_statisticcontroller' => $classPath . 'Controller/StatisticController.php',
	'tx_commerce_statistic' => $classPath . 'Controller/StatisticController.php',
	'tx_commerce_controller_systemdatacontroller' => $classPath . 'Controller/SystemdataController.php',
	'tx_commerce_systemdata' => $classPath . 'Controller/SystemdataController.php',

	/* frontend controller */
	'tx_commerce_controller_basecontroller' => $classPath . 'Controller/BaseController.php',
	'tx_commerce_pibase' => $classPath . 'Controller/BaseController.php',
	'tx_commerce_controller_addressescontroller' => $classPath . 'Controller/AddressesController.php',
	'tx_commerce_pi4' => $classPath . 'Controller/AddressesController.php',
	'tx_commerce_controller_basketcontroller' => $classPath . 'Controller/BasketController.php',
	'tx_commerce_pi2' => $classPath . 'Controller/BasketController.php',
	'tx_commerce_controller_checkoutcontroller' => $classPath . 'Controller/CheckoutController.php',
	'tx_commerce_pi3' => $classPath . 'Controller/CheckoutController.php',
	'tx_commerce_controller_invoicecontroller' => $classPath . 'Controller/InvoiceController.php',
	'tx_commerce_pi6' => $classPath . 'Controller/InvoiceController.php',
	'tx_commerce_controller_listcontroller' => $classPath . 'Controller/ListController.php',
	'tx_commerce_pi1' => $classPath . 'Controller/ListController.php',

	/* data access objects */
	'tx_commerce_dao_addressdao' => $classPath . 'Dao/AddressDao.php',
	'tx_commerce_dao_addressdaomapper' => $classPath . 'Dao/AddressDaoMapper.php',
	'tx_commerce_dao_addressdaoobject' => $classPath . 'Dao/AddressDaoObject.php',
	'tx_commerce_dao_addressdaoparser' => $classPath . 'Dao/AddressDaoParser.php',
	'tx_commerce_dao_addressobserver' => $classPath . 'Dao/AddressObserver.php',
	'tx_commerce_dao_basicdao' => $classPath . 'Dao/BasicDao.php',
	'tx_commerce_dao_basicdaomapper' => $classPath . 'Dao/BasicDaoMapper.php',
	'tx_commerce_dao_basicdaoobject' => $classPath . 'Dao/BasicDaoObject.php',
	'tx_commerce_dao_basicdaoparser' => $classPath . 'Dao/BasicDaoParser.php',
	'tx_commerce_dao_feuserdao' => $classPath . 'Dao/FeuserDao.php',
	'tx_commerce_dao_feuserdaomapper' => $classPath . 'Dao/FeuserDaoMapper.php',
	'tx_commerce_dao_feuserdaoobject' => $classPath . 'Dao/FeuserDaoObject.php',
	'tx_commerce_dao_feuserdaoparser' => $classPath . 'Dao/FeuserDaoParser.php',
	'tx_commerce_dao_feuserobserver' => $classPath . 'Dao/FeuserObserver.php',
	'tx_commerce_dao_feuseraddressfieldmapper' => $classPath . 'Dao/FeuserAddressFieldmapper.php',

	/* domain models */
	'tx_commerce_domain_model_abstractentity' => $classPath . 'Domain/Model/AbstractEntity.php',
	'tx_commerce_element_alib' => $classPath . 'Domain/Model/AbstractEntity.php',
	'tx_commerce_domain_model_article' => $classPath . 'Domain/Model/Article.php',
	'tx_commerce_article' => $classPath . 'Domain/Model/Article.php',
	'tx_commerce_domain_model_articleprice' => $classPath . 'Domain/Model/ArticlePrice.php',
	'tx_commerce_article_price' => $classPath . 'Domain/Model/ArticlePrice.php',
	'tx_commerce_domain_model_attribute' => $classPath . 'Domain/Model/Attribute.php',
	'tx_commerce_attribute' => $classPath . 'Domain/Model/Attribute.php',
	'tx_commerce_domain_model_attributevalue' => $classPath . 'Domain/Model/AttributeValue.php',
	'tx_commerce_attribute_value' => $classPath . 'Domain/Model/AttributeValue.php',
	'tx_commerce_domain_model_basicbasket' => $classPath . 'Domain/Model/BasicBasket.php',
	'tx_commerce_basic_basket' => $classPath . 'Domain/Model/BasicBasket.php',
	'tx_commerce_domain_model_basket' => $classPath . 'Domain/Model/Basket.php',
	'tx_commerce_basket' => $classPath . 'Domain/Model/Basket.php',
	'tx_commerce_domain_model_basketitem' => $classPath . 'Domain/Model/BasketItem.php',
	'tx_commerce_basket_item' => $classPath . 'Domain/Model/BasketItem.php',
	'tx_commerce_domain_model_category' => $classPath . 'Domain/Model/Category.php',
	'tx_commerce_category' => $classPath . 'Domain/Model/Category.php',
	'tx_commerce_domain_model_product' => $classPath . 'Domain/Model/Product.php',
	'tx_commerce_product' => $classPath . 'Domain/Model/Product.php',

	/* domain repository */
	'tx_commerce_domain_repository_repository' => $classPath . 'Domain/Repository/Repository.php',
	'tx_commerce_db_alib' => $classPath . 'Domain/Repository/Repository.php',
	'tx_commerce_domain_repository_articlerepository' => $classPath . 'Domain/Repository/ArticleRepository.php',
	'tx_commerce_db_article' => $classPath . 'Domain/Repository/ArticleRepository.php',
	'tx_commerce_domain_repository_articlepricerepository' => $classPath . 'Domain/Repository/ArticlePriceRepository.php',
	'tx_commerce_db_price' => $classPath . 'Domain/Repository/ArticlePriceRepository.php',
	'tx_commerce_domain_repository_attributerepository' => $classPath . 'Domain/Repository/AttributeRepository.php',
	'tx_commerce_db_attribute' => $classPath . 'Domain/Repository/AttributeRepository.php',
	'tx_commerce_domain_repository_attributevaluerepository' => $classPath . 'Domain/Repository/AttributeValueRepository.php',
	'tx_commerce_db_attribute_value' => $classPath . 'Domain/Repository/AttributeValueRepository.php',
	'tx_commerce_domain_repository_categoryrepository' => $classPath . 'Domain/Repository/CategoryRepository.php',
	'tx_commerce_db_category' => $classPath . 'Domain/Repository/CategoryRepository.php',
	'tx_commerce_domain_repository_folderrepository' => $classPath . 'Domain/Repository/FolderRepository.php',
	'tx_commerce_folder_db' => $classPath . 'Domain/Repository/FolderRepository.php',
	'tx_commerce_domain_repository_productrepository' => $classPath . 'Domain/Repository/ProductRepository.php',
	'tx_commerce_db_product' => $classPath . 'Domain/Repository/ProductRepository.php',

	/* module related classes */
	'tx_commerce_module_access_navigation' => $classPath . 'Module/Access/navigation.php',
	'tx_commerce_module_category_navigation' => $classPath . 'Module/Category/navigation.php',

	/* payment */
	'tx_commerce_payment_abstract' => $classPath . 'Payment/class.tx_commerce_payment_abstract.php',
	'tx_commerce_payment_cashondelivery' => $classPath . 'Payment/class.tx_commerce_payment_cashondelivery.php',
	'tx_commerce_payment_ccvs' => $classPath . 'Payment/Ccvs.php',
	'tx_commerce_payment_creditcard' => $classPath . 'Payment/class.tx_commerce_payment_creditcard.php',
	'tx_commerce_payment_debit' => $classPath . 'Payment/class.tx_commerce_payment_debit.php',
	'tx_commerce_payment_invoice' => $classPath . 'Payment/class.tx_commerce_payment_invoice.php',
	'tx_commerce_payment_prepayment' => $classPath . 'Payment/class.tx_commerce_payment_prepayment.php',
	'creditcardvalidationsolution' => $classPath . 'Payment/Ccvs/CreditCardValidationSolution.php',
	'tx_commerce_payment_criterion_abstract' => $classPath . 'Payment/criteria/class.tx_commerce_payment_criterion_abstract.php',
	'tx_commerce_payment_criterion' => $classPath . 'Payment/criteria/interface.tx_commerce_payment_criterion.php',
	'tx_commerce_payment' => $classPath . 'Payment/interface.tx_commerce_payment.php',
	'payment' => $classPath . 'Payment/class.payment.php',
	'wirecard' => $classPath . 'Payment/class.wirecard.php',
	'tx_commerce_payment_provider_abstract' => $classPath . 'Payment/provider/class.tx_commerce_payment_provider_abstract.php',
	'tx_commerce_payment_provider_wirecard' => $classPath . 'Payment/provider/class.tx_commerce_payment_provider_wirecard.php',
	'tx_commerce_payment_provider_criterion_abstract' => $classPath . 'Payment/provider/criteria/class.tx_commerce_payment_provider_criterion_abstract.php',
	'tx_commerce_payment_provider_criterion' => $classPath . 'Payment/provider/criteria/interface.tx_commerce_payment_provider_criterion.php',
	'tx_commerce_payment_provider' => $classPath . 'Payment/provider/interface.tx_commerce_payment_provider.php',
		// fix missing file
	'tx_commerce_payment_wirecard_lib' => $extensionPath . 'payment/libs/class.tx_commerce_payment_wirecard_lib.php',

	/* task */
	'tx_commerce_task_statistictask' => $classPath . 'Task/StatisticTask.php',
	'tx_commerce_task_statistictaskadditionalfieldprovider' => $classPath . 'Task/StatisticTaskAdditionalFieldProvider.php',

	/* tree */
	'browsetree' => $classPath . 'Tree/class.browsetree.php',
	'langbase' => $classPath . 'Tree/class.langbase.php',
	'leaf' => $classPath . 'Tree/class.leaf.php',
	'leafdata' => $classPath . 'Tree/class.leafData.php',
	'leafmaster' => $classPath . 'Tree/class.leafMaster.php',
	'leafmasterdata' => $classPath . 'Tree/class.leafMasterData.php',
	'leafslave' => $classPath . 'Tree/class.leafSlave.php',
	'leafslavedata' => $classPath . 'Tree/class.leafSlaveData.php',
	'leafview' => $classPath . 'Tree/class.leafView.php',
	'mounts' => $classPath . 'Tree/class.mounts.php',
	'tx_commerce_categorymounts' => $classPath . 'Tree/class.tx_commerce_categorymounts.php',
	'tx_commerce_categorytree' => $classPath . 'Tree/class.tx_commerce_categorytree.php',
	'tx_commerce_leaf_article' => $classPath . 'Tree/class.tx_commerce_leaf_article.php',
	'tx_commerce_leaf_articledata' => $classPath . 'Tree/class.tx_commerce_leaf_articledata.php',
	'tx_commerce_leaf_articleview' => $classPath . 'Tree/class.tx_commerce_leaf_articleview.php',
	'tx_commerce_leaf_category' => $classPath . 'Tree/class.tx_commerce_leaf_category.php',
	'tx_commerce_leaf_categorydata' => $classPath . 'Tree/class.tx_commerce_leaf_categorydata.php',
	'tx_commerce_leaf_categoryview' => $classPath . 'Tree/class.tx_commerce_leaf_categoryview.php',
	'tx_commerce_leaf_product' => $classPath . 'Tree/class.tx_commerce_leaf_product.php',
	'tx_commerce_leaf_productdata' => $classPath . 'Tree/class.tx_commerce_leaf_productdata.php',
	'tx_commerce_leaf_productview' => $classPath . 'Tree/class.tx_commerce_leaf_productview.php',
	'tx_commerce_tree_ordertree' => $classPath . 'Tree/OrderTree.php',
	'tx_commerce_order_pagetree' => $classPath . 'Tree/OrderTree.php',
	'tx_commerce_tree_statistictree' => $classPath . 'Tree/StatisticTree.php',
	'tx_commerce_statistic_pagetree' => $classPath . 'Tree/StatisticTree.php',
	'tx_commerce_treelib_link_categorytree' => $classPath . 'Tree/Link/class.tx_commerce_treelib_link_categorytree.php',
	'tx_commerce_treelib_link_leaf_categoryview' => $classPath . 'Tree/Link/class.tx_commerce_treelib_link_leaf_categoryview.php',
	'tx_commerce_treelib_link_leaf_productview' => $classPath . 'Tree/Link/class.tx_commerce_treelib_link_leaf_productview.php',

	/* utilities */
	'tx_commerce_utility_articlecreatorutility' => $classPath . 'Utility/ArticleCreatorUtility.php',
	'tx_commerce_utility_attributeeditorutility' => $classPath . 'Utility/AttributeEditorUtility.php',
	'tx_commerce_utility_backendutility' => $classPath . 'Utility/BackendUtility.php',
	'tx_commerce_utility_datahandlerutility' => $classPath . 'Utility/DataHandlerUtility.php',
	'sc_tx_commerce_cce_db' => $classPath . 'Utility/DataHandlerUtility.php',
	'tx_commerce_utility_generalutility' => $classPath . 'Utility/class.tx_commerce_div.php',
	'tx_commerce_div' => $classPath . 'Utility/class.tx_commerce_div.php',
	'tx_commerce_belib' => $classPath . 'Utility/BackendUtility.php',
	'tx_commerce_utility_folderutility' => $classPath . 'Utility/FolderUtility.php',
	'tx_commerce_create_folder' => $classPath . 'Utility/FolderUtility.php',
	'tx_commerce_utility_statisticsutility' => $classPath . 'Utility/StatisticsUtility.php',
	'tx_commerce_statistics' => $classPath . 'Utility/StatisticsUtility.php',
	'tx_commerce_utility_tceformsutility' => $classPath . 'Utility/TceformsUtility.php',
	'tx_commerce_forms_select' => $classPath . 'Utility/TceformsUtility.php',
	'tx_commerce_utility_updateutility' => $classPath . 'Utility/UpdateUtility.php',


	/* ViewHelpers */
	'tx_commerce_db_list' => $classPath . 'ViewHelpers/class.tx_commerce_db_list.php',
	'commercerecordlist' => $classPath . 'ViewHelpers/class.tx_commerce_db_list_extra.php',
	'tx_commerce_feusers_localrecordlist' => $classPath . 'ViewHelpers/class.tx_commerce_feusers_localrecordlist.php',
	'tx_commerce_navigation' => $classPath . 'ViewHelpers/class.tx_commerce_navigation.php',
	'tx_commerce_order_localrecordlist' => $classPath . 'ViewHelpers/class.tx_commerce_order_localrecordlist.php',
	'tx_commerce_tcefunc' => $classPath . 'ViewHelpers/class.tx_commerce_tcefunc.php',
	'tx_commerce_treelib_browser' => $classPath . 'ViewHelpers/class.tx_commerce_treelib_browser.php',
	'tx_commerce_treelib_tceforms' => $classPath . 'ViewHelpers/class.tx_commerce_treelib_tceforms.php',
	'user_attributeedit_func' => $classPath . 'ViewHelpers/class.user_attributeedit_func.php',
	'user_orderedit_func' => $classPath . 'ViewHelpers/class.user_orderedit_func.php',

	'tx_moneylib' => t3lib_extMgm::extPath('moneylib') . 'class.tx_moneylib.php',
	'tx_staticinfotables_pi1' => t3lib_extMgm::extPath('static_info_tables') . 'pi1/class.tx_staticinfotables_pi1.php',

	'recordlist' => PATH_typo3 . 'class.db_list.inc',
	'localrecordlist' => PATH_typo3 . 'class.db_list_extra.inc',
	'sc_mod_web_perm_ajax' => PATH_typo3 . 'sysext/perm/mod1/class.sc_mod_web_perm_ajax.php',
);

?>