<?php

/**
 * Credit Card Validation Solution, PHP Edition,
 * English language error messages.
 *
 * @package    CreditCardValidationSolution
 * @author     Daniel Convissor <danielc@analysisandsolutions.com>
 * @copyright  The Analysis and Solutions Company, 2002-2006
 * @version    $Name: rel-5-13 $ $Id: ccvs_en.inc,v 1.3 2006/03/18 17:31:31 danielc Exp $
 * @link       http://www.analysisandsolutions.com/software/ccvs/ccvs.htm
 */

/** */
$CCVSErrNumberString = 'CCVSErrNumberString';
$CCVSErrVisa14       = 'CCVSErrVisa14';
$CCVSErrUnknown      = 'CCVSErrUnknown';
$CCVSErrAccepted     = 'CCVSErrAccepted';
$CCVSErrNoAccept     = 'CCVSErrNoAccept';
$CCVSErrShort        = 'CCVSErrShort';
$CCVSErrLong         = 'CCVSErrLong';
$CCVSErrChecksum     = 'CCVSErrChecksum';
$CCVSErrMonthString  = 'CCVSErrMonthString';
$CCVSErrMonthFormat  = 'CCVSErrMonthFormat';
$CCVSErrYearString   = 'CCVSErrYearString';
$CCVSErrYearFormat   = 'CCVSErrYearFormat';
$CCVSErrExpired      = 'CCVSErrExpired';
$CCVSErrCheckNumber  = 'CCVSErrCheckNumber';

?>