<?php
return array(
	'SC_mod_access_perm_index' => 'Tx_Commerce_Controller_AccessController',
	'tx_commerce_pi4' => 'Tx_Commerce_Controller_AddressesController',
	'tx_commerce_pibase' => 'Tx_Commerce_Controller_BaseController',
	'tx_commerce_pi2' => 'Tx_Commerce_Controller_BasketController',
	'tx_commerce_categories' => 'Tx_Commerce_Controller_CategoriesController',
	'tx_commerce_pi3' => 'Tx_Commerce_Controller_CheckoutController',
	'tx_commerce_pi6' => 'Tx_Commerce_Controller_InvoiceController',
	'tx_commerce_pi1' => 'Tx_Commerce_Controller_ListController',
	'tx_commerce_orders' => 'Tx_Commerce_Controller_OrdersController',
	'SC_mod_access_perm_ajax' => 'Tx_Commerce_Controller_PermissionAjaxController',
	'tx_commerce_statistic' => 'Tx_Commerce_Controller_StatisticController',
	'Tx_Commerce_SystemData' => 'Tx_Commerce_Controller_SystemdataController',
	'tx_commerce_cmd_wizard' => 'Tx_Commerce_Controller_WizardController',
	'tx_commerce_db_category' => 'Tx_Commerce_Domain_Repository_CategoryRepository',

	'tx_commerce_element_alib' => 'Tx_Commerce_Domain_Model_AbstractEntity',
	'tx_commerce_article' => 'Tx_Commerce_Domain_Model_Article',
	'tx_commerce_article_price' => 'Tx_Commerce_Domain_Model_ArticlePrice',
	'tx_commerce_attribute' => 'Tx_Commerce_Domain_Model_Attribute',
	'tx_commerce_attribute_value' => 'Tx_Commerce_Domain_Model_AttributeValue',
	'tx_commerce_basic_basket' => 'Tx_Commerce_Domain_Model_BasicBasket',
	'tx_commerce_basket' => 'Tx_Commerce_Domain_Model_Basket',
	'tx_commerce_basket_item' => 'Tx_Commerce_Domain_Model_BasketItem',
	'tx_commerce_category' => 'Tx_Commerce_Domain_Model_Category',
	'tx_commerce_product' => 'Tx_Commerce_Domain_Model_Product',

	'tx_commerce_db_price' => 'Tx_Commerce_Domain_Repository_ArticlePriceRepository',
	'tx_commerce_db_article' => 'Tx_Commerce_Domain_Repository_ArticleRepository',
	'tx_commerce_db_attribute' => 'Tx_Commerce_Domain_Repository_AttributeRepository',
	'tx_commerce_db_attribute_value' => 'Tx_Commerce_Domain_Repository_AttributeValueRepository',
	'tx_commerce_folder_db' => 'Tx_Commerce_Domain_Repository_FolderRepository',
	'tx_commerce_db_product' => 'Tx_Commerce_Domain_Repository_ProductRepository',
	'tx_commerce_db_alib' => 'Tx_Commerce_Domain_Repository_Repository',

	'payment' => 'Tx_Commerce_Payment_Payment',
	'tx_commerce_payment_abstract' => 'Tx_Commerce_Payment_PaymentAbstract',
	'wirecard' => 'Tx_Commerce_Payment_Wirecard',
	'tx_commerce_payment_criterion_abstract' => 'Tx_Commerce_Payment_Criterion_CriterionAbstract',
	'tx_commerce_payment_provider_criterion_abstract' => 'Tx_Commerce_Payment_Criterion_ProviderCriterionAbstract',
	'tx_commerce_payment_provider_abstract' => 'Tx_Commerce_Payment_Provider_ProviderAbstract',

	'browsetree' => 'Tx_Commerce_Tree_Browsetree',
	'tx_commerce_categorytree' => 'Tx_Commerce_Tree_CategoryTree',
	'tx_commerce_order_pagetree' => 'Tx_Commerce_Tree_OrderTree',
	'tx_commerce_statistic_pagetree' => 'Tx_Commerce_Tree_StatisticTree',

	'tx_commerce_categorymounts' => 'Tx_Commerce_Tree_CategoryMounts',
	'tx_commerce_leaf_article' => 'Tx_Commerce_Tree_Leaf_Article',
	'tx_commerce_leaf_articledata' => 'Tx_Commerce_Tree_Leaf_ArticleData',
	'tx_commerce_leaf_articleview' => 'Tx_Commerce_Tree_Leaf_ArticleView',
	'langbase' => 'Tx_Commerce_Tree_Leaf_Base',
	'tx_commerce_leaf_category' => 'Tx_Commerce_Tree_Leaf_Category',
	'tx_commerce_leaf_categorydata' => 'Tx_Commerce_Tree_Leaf_CategoryData',
	'tx_commerce_leaf_categoryview' => 'Tx_Commerce_Tree_Leaf_CategoryView',
	'leafData' => 'Tx_Commerce_Tree_Leaf_Data',
	'leaf' => 'Tx_Commerce_Tree_Leaf_Leaf',
	'leafMaster' => 'Tx_Commerce_Tree_Leaf_Master',
	'leafMasterData' => 'Tx_Commerce_Tree_Leaf_MasterData',
	'mounts' => 'Tx_Commerce_Tree_Leaf_Mounts',
	'tx_commerce_leaf_product' => 'Tx_Commerce_Tree_Leaf_Product',
	'tx_commerce_leaf_productdata' => 'Tx_Commerce_Tree_Leaf_ProductData',
	'tx_commerce_leaf_productview' => 'Tx_Commerce_Tree_Leaf_ProductView',
	'leafSlave' => 'Tx_Commerce_Tree_Leaf_Slave',
	'leafSlaveData' => 'Tx_Commerce_Tree_Leaf_SlaveData',
	'leafView' => 'Tx_Commerce_Tree_Leaf_View',

	'tx_commerce_attributeEditor' => 'Tx_Commerce_Utility_AttributeEditorUtility',
	'tx_commerce_belib' => 'Tx_Commerce_Utility_BackendUtility',
	'tx_commerce_clickmenu' => 'Tx_Commerce_Utility_ClickmenuUtility',
	'SC_tx_commerce_cce_db' => 'Tx_Commerce_Utility_DataHandlerUtility',
	'tx_commerce_create_folder' => 'Tx_Commerce_Utility_FolderUtility',
	'tx_commerce_div' => 'Tx_Commerce_Utility_GeneralUtility',
	'tx_commerce_statistics' => 'Tx_Commerce_Utility_StatisticsUtility',
	'tx_commerce_forms_select' => 'Tx_Commerce_Utility_TceformsUtility',

	'user_attributeedit_func' => 'Tx_Commerce_ViewHelpers_AttributeEditFunc',
	'commerceRecordList' => 'Tx_Commerce_ViewHelpers_CategoryRecordList',
	'tx_commerce_feusers_localRecordlist' => 'Tx_Commerce_ViewHelpers_FeuserRecordList',
	'tx_commerce_navigation' => 'Tx_Commerce_ViewHelpers_Navigation',
	'user_orderedit_func' => 'Tx_Commerce_ViewHelpers_OrderEditFunc',
	'tx_commerce_order_localRecordlist' => 'Tx_Commerce_ViewHelpers_OrderRecordList',
	'tx_commerce_tceFunc' => 'Tx_Commerce_ViewHelpers_TceFunc',
	'tx_commerce_treelib_browser' => 'Tx_Commerce_ViewHelpers_TreelibBrowser',
	'tx_commerce_treelib_tceforms' => 'Tx_Commerce_ViewHelpers_TreelibTceforms',

	'tx_commerce_treelib_link_categorytree' => 'Tx_Commerce_ViewHelpers_Browselinks_CategoryTree',
	'tx_commerce_treelib_link_leaf_categoryview' => 'Tx_Commerce_ViewHelpers_Browselinks_CategoryView',
	'tx_commerce_treelib_link_leaf_productview' => 'Tx_Commerce_ViewHelpers_Browselinks_ProductView',
);